document.querySelectorAll('img[src="assets/mvm-logo.svg"]').forEach(img=>{img.src='assets/mvm-logo-blue.webp';img.alt=img.closest('.brand,.footer-brand')?'MVM Yavaşlar Yapı Market logosu':''});const favicon=document.querySelector('link[rel="icon"]');if(favicon){favicon.href='assets/mvm-logo-blue.webp';favicon.type='image/webp'}
document.getElementById('year').textContent=new Date().getFullYear();
const menu=document.querySelector('.menu'),nav=document.getElementById('nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
const board=document.querySelector('.board'),slides=[...board.querySelectorAll('.slide')],dots=[...board.querySelectorAll('.dots button')],counter=board.querySelector('.counter');let current=0,timer;function show(i){current=(i+slides.length)%slides.length;slides.forEach((s,n)=>{s.classList.toggle('active',n===current);s.setAttribute('aria-hidden',String(n!==current))});dots.forEach((d,n)=>{d.classList.toggle('active',n===current);d.setAttribute('aria-selected',String(n===current))});const activeSlide=slides[current];board.style.setProperty('--board-bg',activeSlide.style.getPropertyValue('--slide-bg'));board.style.setProperty('--board-pos',activeSlide.style.getPropertyValue('--bg-pos')||'center');counter.textContent=`${String(current+1).padStart(2,'0')} / ${String(slides.length).padStart(2,'0')}`}function play(){clearInterval(timer);if(!matchMedia('(prefers-reduced-motion:reduce)').matches)timer=setInterval(()=>show(current+1),5500)}board.querySelector('.prev').onclick=()=>{show(current-1);play()};board.querySelector('.next').onclick=()=>{show(current+1);play()};dots.forEach((d,i)=>d.onclick=()=>{show(i);play()});board.onmouseenter=()=>clearInterval(timer);board.onmouseleave=play;show(0);play();
const categories=document.getElementById('urunler');
const brands=[['DYO','Boya ürünleri','https://www.dyo.com.tr/','dyo.com.tr'],['Bianca','Boya ürünleri','https://www.bianca.com.tr/','bianca.com.tr'],['İSONEM','Yalıtım çözümleri','https://isonem.com.tr/','isonem.com.tr'],['Kalde','Boru sistemleri','https://kalde.com/','kalde.com'],['CMS','Batarya grubu','https://www.curkuslar.com.tr/','curkuslar.com.tr'],['Kale','Batarya ve vitrifiye','https://www.kale.com.tr/','kale.com.tr'],['VitrA','Banyo ürünleri','https://www.vitra.com.tr/','vitra.com.tr'],['Artema','Armatür ve batarya','https://www.artema.com.tr/','artema.com.tr'],['SIBAX','Yapı ürünleri','https://www.sibakimya.com.tr/','sibakimya.com.tr'],['Henkel','Yapıştırıcı ve kimyasallar','https://www.henkel-adhesives.com/tr/tr.html','henkel-adhesives.com']];
categories.insertAdjacentHTML('beforebegin',`<section class="store-tools" aria-labelledby="urun-arama-baslik"><div class="tool-head"><div><p class="eyebrow">Ürün arama</p><h2 id="urun-arama-baslik">Mağazada aradığınız ürünü bulun</h2></div><p>Ürün, kullanım alanı veya kategori yazın; uygun ürün grupları anında listelensin.</p></div><form class="quick-search" role="search"><input type="search" aria-label="Ürünlerde ara" placeholder="Örn. boya, batarya, priz, vida..."><button type="submit">Ürünlerde ara</button><button type="button" class="search-clear" hidden>Temizle</button></form><div class="quick-chips" aria-label="Popüler aramalar"><button type="button" data-query="Boya">Boya</button><button type="button" data-query="Tesisat">Tesisat</button><button type="button" data-query="Elektrik">Elektrik</button><button type="button" data-query="El Aletleri">El Aletleri</button><button type="button" data-query="Yapı">Yapı</button><button type="button" data-query="Bahçe">Bahçe</button></div><a class="search-whatsapp" href="https://wa.me/905389705265?text=Merhaba%20MVM%20Yava%C5%9Flar%20Yap%C4%B1%20Market%2C%20arad%C4%B1%C4%9F%C4%B1m%20%C3%BCr%C3%BCn%C3%BC%20bulamad%C4%B1m." target="_blank" rel="noopener">Aradığınızı bulamadınız mı? WhatsApp’tan sorun →</a></section><section class="brand-showcase" id="bayilikler"><p class="eyebrow">Güvenilir markalar, güçlü ürün seçenekleri</p><h2>Bayiliklerimiz ve Markalarımız</h2><p class="brand-intro">Boya, tesisat, batarya, vitrifiye ve yapı kimyasallarında ihtiyaç duyduğunuz markaları mağazamızda bulabilirsiniz.</p><div class="brand-row">${brands.map(([name,type,url,domain])=>`<a href="${url}" target="_blank" rel="noopener" aria-label="${name} resmî web sitesi"><img src="https://www.google.com/s2/favicons?domain=${domain}&sz=128" alt="" width="42" height="42" loading="lazy"><span><b>${name}</b><small>${type}</small></span></a>`).join('')}</div><p class="brand-note">Markaya dokunarak markanın resmî web sitesini açabilirsiniz.</p></section>`);
document.getElementById('hakkimizda').insertAdjacentHTML('beforebegin',`<section class="promo-banner"><div><p class="eyebrow">Mağazaya özel</p><h2>Güncel kampanya ve stok bilgisi cebinizde</h2><p>İhtiyacınız olan ürünü yazın, size hızlıca dönüş yapalım.</p></div><a href="https://wa.me/905389705265" target="_blank" rel="noopener">WhatsApp’tan bilgi alın →</a></section>`);
const products=[
['Boya','DYO Tavan Boyası 17,5 kg','İç mekân tavanlarında mat ve homojen görünüm sağlayan tavan boyası.','assets/dyo-tavan-17-5kg.webp','center','DYO','17,5 kg','Güncel kampanya'],
['Boya','DYO Dyoplast 15 L','İç cephe duvarları için mat görünümlü plastik boya.','assets/dyoplast-15lt.webp','center','DYO','15 litre','Güncel kampanya'],
['Boya','DYO Dinamik 15 L','Silikon katkılı, silinebilir ve ipek mat iç cephe boyası.','assets/dyo-dinamik-15lt.webp','center','DYO','15 litre','Güncel kampanya'],
['Yalıtım','DYO Dyoflex Elyaflı 20 kg','Elyaf katkılı, elastik sıvı çatı izolasyon malzemesi.','assets/dyoflex-elyafli-20kg.webp','center','DYO','20 kg','Haftanın fırsatı'],
['Yalıtım','İSONEM L Şeffaf Güç','Görünümü kapatmadan koruma sağlayan, su bazlı şeffaf yalıtım ürünü.','assets/isonem-l-seffaf-guc.webp','center','İSONEM','Ambalaj seçeneği','Öne çıkan'],
['Yapı','İSONEM Jelbeton 20 kg','İç ve dış mekânlar için kendiliğinden yayılan renkli zemin kaplaması.','assets/isonem-jelbeton.webp','center','İSONEM','20 kg','Öne çıkan'],
['El Aletleri','Şarjlı ve Elektrikli Aletler','Matkap ve işinizi kolaylaştıran elektrikli el aletleri.','assets/store-products-v2.webp','36% center','Çeşitli markalar','Mağaza seçkisi','Ürün grubu'],
['El Aletleri','El Aletleri','Tornavida, pense, çekiç ve ölçüm ürünleri.','assets/kategori-el-aletleri.webp','center','Çeşitli markalar','Mağaza seçkisi','Ürün grubu'],
['Boya','Boya Yardımcıları','Fırça, rulo, bant ve uygulama malzemeleri.','assets/kategori-boya-dekorasyon.webp','78% center','Çeşitli markalar','Mağaza seçkisi','Ürün grubu'],
['Tesisat','Musluk, Batarya ve Tesisat','Mutfak ve banyo için batarya, vana ve bağlantı parçaları.','assets/kategori-tesisat.webp','25% center','Kalde · CMS · Artema','Mağaza seçkisi','Ürün grubu'],
['Elektrik','Priz, Anahtar ve Aydınlatma','Ev ve iş yerleri için elektrik tesisatı ürünleri.','assets/kategori-elektrik.webp','60% center','Çeşitli markalar','Mağaza seçkisi','Ürün grubu'],
['Yapı','Yapı Kimyasalları ve Montaj','Silikon, mastik, yapıştırıcı, vida ve dübel ürünleri.','assets/kategori-yapi-malzemeleri.webp','70% center','Henkel · SIBAX','Mağaza seçkisi','Ürün grubu'],
['Bahçe','Bahçe ve Sulama Ekipmanları','Bakım, sulama ve günlük bahçe işleri için ürünler.','assets/kategori-bahce-hirdavat.webp','center','Çeşitli markalar','Mağaza seçkisi','Ürün grubu'],
['Hırdavat','Genel Hırdavat','Tamiratlarda ihtiyaç duyulan pratik çözümler.','assets/kategori-el-aletleri.webp','62% center','Çeşitli markalar','Mağaza seçkisi','Ürün grubu']
];
const catalog=`<section class="catalog" id="urun-vitrini"><div class="catalog-head"><div><p class="eyebrow">Ürün vitrini</p><h2>Mağaza ürünlerini keşfedin</h2></div><p>Ürünleri inceleyin, sepetinize ekleyin; stok teyidinden sonra mağazadan teslim alıp mağazada ödeyin.</p></div><div class="catalog-assurance"><span>✓ Online ödeme yok</span><span>✓ Stok teyidi mağazadan</span><span>✓ Teslim alma zamanı sizden</span></div><div class="filters" role="group" aria-label="Ürün filtresi"></div><p class="result-count" aria-live="polite"></p><div class="product-grid"></div><div class="catalog-empty" hidden></div></section>`;
document.querySelector('.store-tools').insertAdjacentHTML('afterend',catalog);
const grid=document.querySelector('.product-grid'),filterBox=document.querySelector('.filters'),count=document.querySelector('.result-count'),empty=document.querySelector('.catalog-empty'),form=document.querySelector('.quick-search'),input=form.querySelector('input'),clearSearch=form.querySelector('.search-clear'),groups=['Tümü',...new Set(products.map(p=>p[0]))];
let activeGroup='Tümü',searchQuery='';
const normalize=value=>value.toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
function draw(){
 const needle=normalize(searchQuery.trim());
 const visible=products.filter(([cat,name,desc,image,position,brand,pack,label])=>(activeGroup==='Tümü'||cat===activeGroup)&&(!needle||normalize([cat,name,desc,brand,pack,label].join(' ')).includes(needle)));
 grid.innerHTML=visible.map(([cat,name,desc,image,position,brand,pack,label])=>`<article class="product-item"><div class="product-thumb"><img src="${image}" alt="${name}" width="720" height="480" loading="lazy" style="--thumb-pos:${position}"><span class="product-badge">${label}</span></div><div class="product-copy"><small>${cat}</small><h3>${name}</h3><p>${desc}</p><div class="product-meta"><span>${brand}</span><span>${pack}</span></div><div class="store-price">Güncel fiyat mağazada</div><div class="product-actions"><button class="add-cart" data-add="${name}">Sepete ekle</button><button class="ask-product" data-product="${name}">Stok ve fiyat sor</button></div></div></article>`).join('');
 count.textContent=searchQuery?`“${searchQuery}” için ${visible.length} sonuç bulundu`:`${visible.length} ürün ve ürün grubu gösteriliyor`;
 empty.hidden=visible.length>0;
 empty.innerHTML=visible.length?'':`<strong>Aramanıza uygun ürün bulunamadı.</strong><p>Ürünün adını bize yazın; stok ve fiyat bilgisini mağazamızdan hızlıca öğrenin.</p><a href="https://wa.me/905389705265?text=${encodeURIComponent('Merhaba MVM Yavaşlar Yapı Market, '+searchQuery+' ürününü arıyorum. Stok ve fiyat bilgisi alabilir miyim?')}" target="_blank" rel="noopener">WhatsApp’tan sorun →</a>`;
 clearSearch.hidden=!searchQuery;
 grid.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>openWhatsApp(b.dataset.product));
 grid.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addToCart(b.dataset.add));
}
groups.forEach((g,i)=>filterBox.insertAdjacentHTML('beforeend',`<button class="${i?'':'active'}" data-filter="${g}">${g}</button>`));
function setGroup(group){activeGroup=group;filterBox.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.filter===group));draw()}
filterBox.onclick=e=>{const button=e.target.closest('[data-filter]');if(button)setGroup(button.dataset.filter)};
function runSearch(scroll=false){searchQuery=input.value.trim();activeGroup='Tümü';filterBox.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.filter==='Tümü'));draw();if(scroll)document.getElementById('urun-vitrini').scrollIntoView({behavior:'smooth',block:'start'})}
form.onsubmit=e=>{e.preventDefault();runSearch(true)};
input.oninput=()=>runSearch(false);
clearSearch.onclick=()=>{input.value='';runSearch(false);input.focus()};
document.querySelectorAll('.quick-chips [data-query]').forEach(b=>b.onclick=()=>{input.value=b.dataset.query;runSearch(true)});
draw();
const campaignProducts={'Dyoflex Elyaflı 20 kg':'DYO Dyoflex Elyaflı 20 kg','DYO Tavan 17,5 kg':'DYO Tavan Boyası 17,5 kg','Dyoplast 15 L':'DYO Dyoplast 15 L','DYO Dinamik 15 L':'DYO Dinamik 15 L'};
document.querySelectorAll('.campaigns article').forEach(card=>{const title=card.querySelector('h3')?.textContent.trim(),name=campaignProducts[title];if(!name)return;const link=card.querySelector('a');link.insertAdjacentHTML('afterend',`<button type="button" class="campaign-add" data-campaign-add="${name}">Sepete ekle</button>`);card.querySelector('[data-campaign-add]').onclick=()=>addToCart(name)});
function openWhatsApp(product){location.href=`https://wa.me/905389705265?text=${encodeURIComponent('Merhaba MVM Yavaşlar Yapı Market, '+product+' için stok ve fiyat bilgisi almak istiyorum.')}`}
document.getElementById('iletisim').insertAdjacentHTML('beforebegin',`<section class="trust-section"><p class="eyebrow">Neden MVM Yavaşlar?</p><h2>Alışverişinizi kolaylaştıran yerel hizmet</h2><div class="trust-grid"><article><span>💬</span><h3>Hızlı bilgi</h3><p>Ürün, stok ve fiyat için doğrudan mağazaya ulaşın.</p></article><article><span>🧭</span><h3>Doğru ürüne yönlendirme</h3><p>İhtiyacınızı anlatın, uygun ürün grubunu birlikte belirleyelim.</p></article><article><span>📍</span><h3>Kepez’de yakınınızda</h3><p>Ahatlı Mahallesi’ndeki mağazamızdan ürünü inceleyin.</p></article><article><span>🧰</span><h3>Geniş ürün grubu</h3><p>Yapı, boya, elektrik, tesisat ve hırdavat tek noktada.</p></article></div></section><section class="faq"><p class="eyebrow">Merak edilenler</p><h2>Sık sorulan sorular</h2><div class="faq-list"><details><summary>Ürün fiyatlarını sitede neden göremiyorum?</summary><p>Fiyatlar ve kampanyalar değişebildiği için en güncel bilgiyi telefon veya WhatsApp üzerinden iletiyoruz.</p></details><details><summary>Bir ürünün stokta olup olmadığını nasıl öğrenebilirim?</summary><p>Ürün vitrini veya hızlı sorgulama alanından ürünü seçerek hazır WhatsApp mesajı gönderebilirsiniz.</p></details><details><summary>Mağazaya nasıl ulaşabilirim?</summary><p>İletişim bölümündeki Yol Tarifi bağlantısı sizi Ahatlı Mah. Ulusoy Cad. No:66 Kepez / Antalya adresine yönlendirir.</p></details></div></section>`);
document.body.insertAdjacentHTML('beforeend',`<div class="mobile-actions"><a href="tel:+902422272575">☎ Hemen Ara</a><a href="https://wa.me/905389705265">● WhatsApp</a></div>`);

const cartKey='mvm-store-cart-v1';
let cart=JSON.parse(localStorage.getItem(cartKey)||'[]');
document.querySelector('header').insertAdjacentHTML('beforeend','<button class="cart-trigger" type="button" aria-label="Rezervasyon sepetini aç">Sepet <span>0</span></button>');
document.body.insertAdjacentHTML('beforeend',`<div class="cart-backdrop" hidden></div><aside class="cart-drawer" aria-hidden="true" aria-labelledby="cart-title"><div class="cart-top"><div><small>MAĞAZADAN TESLİM</small><h2 id="cart-title">Rezervasyon sepetiniz</h2></div><button class="cart-close" aria-label="Sepeti kapat">×</button></div><div class="cart-info">Ürünleri ayırtın, stok onayından sonra mağazamızdan teslim alın ve ödemenizi mağazada yapın.</div><div class="cart-items"></div><div class="cart-empty"><strong>Sepetiniz henüz boş</strong><p>Ürün vitrininden ürün gruplarını ekleyebilirsiniz.</p><a href="#urun-vitrini">Ürünleri incele</a></div><form class="pickup-form"><h3>Teslim alma bilgileri</h3><label>Ad soyad<input name="name" autocomplete="name" required placeholder="Adınız ve soyadınız"></label><label>Telefon<input name="phone" autocomplete="tel" inputmode="tel" required placeholder="05xx xxx xx xx"></label><label>Teslim alma zamanı<select name="pickup" required><option value="">Seçiniz</option><option>Bugün</option><option>Yarın</option><option>2 gün içinde</option><option>Mağaza beni arasın</option></select></label><label>Notunuz<textarea name="note" rows="2" placeholder="Marka, ölçü, renk veya diğer tercihleriniz"></textarea></label><button class="reserve-button">WhatsApp ile rezervasyon oluştur</button><p class="payment-note">Online ödeme alınmaz. Stok teyidinden sonra ödemenizi mağazada nakit veya kredi kartıyla yapabilirsiniz.</p></form></aside>`);
const cartTrigger=document.querySelector('.cart-trigger'),cartDrawer=document.querySelector('.cart-drawer'),cartBackdrop=document.querySelector('.cart-backdrop'),cartClose=document.querySelector('.cart-close'),cartItems=document.querySelector('.cart-items'),cartEmpty=document.querySelector('.cart-empty'),pickupForm=document.querySelector('.pickup-form');
function saveCart(){localStorage.setItem(cartKey,JSON.stringify(cart));renderCart()}
function addToCart(name){const item=cart.find(x=>x.name===name);if(item)item.qty++;else cart.push({name,qty:1});saveCart();openCart();cartTrigger.classList.remove('cart-pop');void cartTrigger.offsetWidth;cartTrigger.classList.add('cart-pop')}
function renderCart(){const total=cart.reduce((s,x)=>s+x.qty,0);cartTrigger.querySelector('span').textContent=total;cartItems.innerHTML=cart.map((x,i)=>`<article><div><strong>${x.name}</strong><small>Fiyat ve stok mağazada teyit edilir</small></div><div class="qty"><button type="button" data-minus="${i}" aria-label="Azalt">−</button><span>${x.qty}</span><button type="button" data-plus="${i}" aria-label="Artır">+</button></div><button type="button" class="remove-item" data-remove="${i}" aria-label="${x.name} ürününü kaldır">Kaldır</button></article>`).join('');cartEmpty.hidden=cart.length>0;pickupForm.hidden=cart.length===0}
function openCart(){cartDrawer.classList.add('open');cartDrawer.setAttribute('aria-hidden','false');cartBackdrop.hidden=false;document.body.classList.add('cart-open');cartClose.focus()}
function closeCart(){cartDrawer.classList.remove('open');cartDrawer.setAttribute('aria-hidden','true');cartBackdrop.hidden=true;document.body.classList.remove('cart-open');cartTrigger.focus()}
cartTrigger.onclick=openCart;cartClose.onclick=closeCart;cartBackdrop.onclick=closeCart;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&cartDrawer.classList.contains('open'))closeCart()});
cartItems.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.plus!==undefined)cart[+b.dataset.plus].qty++;if(b.dataset.minus!==undefined){const i=+b.dataset.minus;cart[i].qty--;if(cart[i].qty<1)cart.splice(i,1)}if(b.dataset.remove!==undefined)cart.splice(+b.dataset.remove,1);saveCart()};
cartEmpty.querySelector('a').onclick=closeCart;
pickupForm.onsubmit=e=>{e.preventDefault();if(!cart.length)return;const data=new FormData(pickupForm);const order='MVM-'+Date.now().toString().slice(-6);const list=cart.map(x=>'• '+x.name+' — '+x.qty+' adet').join('\n');const message=`Merhaba MVM Yavaşlar Yapı Market, mağazadan teslim rezervasyonu oluşturmak istiyorum.\n\nSipariş No: ${order}\nAd Soyad: ${data.get('name')}\nTelefon: ${data.get('phone')}\nTeslim Alma: ${data.get('pickup')}\n\nÜrünler:\n${list}\n\nNot: ${data.get('note')||'-'}\n\nStok ve fiyat teyidini bekliyorum. Ödemeyi mağazada yapacağım.`;window.open('https://wa.me/905389705265?text='+encodeURIComponent(message),'_blank','noopener')};
renderCart();
